//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrEyni.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityOption
    {
        public int ID { get; set; }
        public Nullable<int> ActivityID { get; set; }
        public Nullable<int> ColumnID { get; set; }
        public string Value { get; set; }
        public Nullable<int> Operator { get; set; }
    }
}
