//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrEyni.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int ID { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> ActivityDate { get; set; }
        public string Adress { get; set; }
        public Nullable<int> City { get; set; }
        public string PlaceName { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<bool> FreeCost { get; set; }
        public Nullable<int> MaxCount { get; set; }
        public Nullable<bool> IsShow { get; set; }
    }
}
