//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrEyni.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityImage
    {
        public int Id { get; set; }
        public Nullable<int> ActivityID { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
    }
}
