//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrEyni.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Child
    {
        public int ID { get; set; }
        public Nullable<int> FamilyChildID { get; set; }
        public string FirstName { get; set; }
        public string TZ { get; set; }
        public Nullable<int> HMOID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> ProblemID { get; set; }
        public string Notes { get; set; }
        public string LastName { get; set; }
    }
}
