//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrEyni.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamilyChild
    {
        public int Id { get; set; }
        public Nullable<int> FamilyId { get; set; }
        public string FirstName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<bool> IsVisionImpaired { get; set; }
    }
}
