//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrEyni.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrEnayEntities : DbContext
    {
        public OrEnayEntities()
            : base("name=OrEnayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<ActivityImage> ActivityImages { get; set; }
        public virtual DbSet<ActivityOption> ActivityOptions { get; set; }
        public virtual DbSet<ActivityRegister> ActivityRegisters { get; set; }
        public virtual DbSet<Child> Children { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Donation> Donations { get; set; }
        public virtual DbSet<Donor> Donors { get; set; }
        public virtual DbSet<DonorContact> DonorContacts { get; set; }
        public virtual DbSet<Family> Families { get; set; }
        public virtual DbSet<FamilyChild> FamilyChilds { get; set; }
        public virtual DbSet<HMO> HMOes { get; set; }
        public virtual DbSet<MaritalStatu> MaritalStatus { get; set; }
        public virtual DbSet<Parent> Parents { get; set; }
        public virtual DbSet<Problem> Problems { get; set; }
        public virtual DbSet<Process> Processes { get; set; }
        public virtual DbSet<ProcessType> ProcessTypes { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
