//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrEyni.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parent
    {
        public int ID { get; set; }
        public Nullable<int> FamilyID { get; set; }
        public string FirstName { get; set; }
        public string Occupation { get; set; }
        public Nullable<bool> IsMother { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> IsVisionImpaired { get; set; }
    }
}
